# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Adminuser.destroy_all
# Targetmessage.destroy_all
# Messhistory.destroy_all
# UserOrg.destroy_all
# Message.destroy_all
# Org.destroy_all
# Target.destroy_all
# User.destroy_all
#Rep.destroy_all
#
#
#
 org1 = Org.create(org_name: "General", org_status: "active")
# Adminuser.create(first_name: "Admin", last_name: "User", email: "test@test", org_id: org1.id)
# u2 = User.create(first_name: "Bob", last_name: "Kiger", enrollment: DateTime.new(2017, 3, 26), email: "bob@comcast.net", password: "Topsecret", password_confirmation: "Topsecret")
# UserOrg.create(user_id: u1.id, org_id: org1.id)
 Message.create(title: "first message", message_text: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ", create_date: DateTime.new(2017, 2, 26), org_id: org1.id)
 Message.create(title: "second message", message_text: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ", create_date: DateTime.new(2017, 2, 27), org_id: org1.id)
 Target.create(first_name: "Nettie", last_name: "Kliger", zip: "94702", address: "", city: "", state: "TX", salutation: "Hi Mom", email: "bkliger@comcast.net", rec_email: "1", rec_text: "1", phone: "203-234-3333", status: "active", user_id: u1.id)
 Target.create(first_name: "Billie", last_name: "James", zip: "77450", address: "4315 Cannondale Lane", city: "Katy", state: "TX",  salutation: "Hi Dad", email: "bkliger@comcast.net", rec_email: "1", rec_text: "0", phone: "203-234-3333", status: "active", user_id: u1.id)
Rep.create(first_name: "Lamar", first_three: "Lam", last_name: "Alexander", url: "http://www.alexander.senate.gov/public/index.cfm?p=Email")
Rep.create(first_name: "Tammy", first_three: "Tam", last_name: "Baldwin", url: "http://www.baldwin.senate.gov/feedback")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Barrasso", url: "http://www.barrasso.senate.gov/public/index.cfm/contact-form")
Rep.create(first_name: "Michael F.", first_three: "Mic", last_name: "Bennet", url: "http://www.bennet.senate.gov/?p=contact")
Rep.create(first_name: "Richard", first_three: "Ric", last_name: "Blumenthal", url: "http://www.blumenthal.senate.gov/contact/")
Rep.create(first_name: "Roy", first_three: "Roy", last_name: "Blunt", url: "http://www.blunt.senate.gov/public/index.cfm/contact-roy")
Rep.create(first_name: "Cory A.", first_three: "Cor", last_name: "Booker", url: "http://www.booker.senate.gov/?p=contact")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Boozman", url: "http://www.boozman.senate.gov/public/index.cfm/contact")
Rep.create(first_name: "Sherrod", first_three: "She", last_name: "Brown", url: "http://www.brown.senate.gov/contact/")
Rep.create(first_name: "Richard", first_three: "Ric", last_name: "Burr", url: "http://www.burr.senate.gov/contact/email")
Rep.create(first_name: "Maria", first_three: "Mar", last_name: "Cantwell", url: "http://www.cantwell.senate.gov/public/index.cfm/email-maria")
Rep.create(first_name: "Shelley Moore", first_three: "She", last_name: "Capito", url: "http://www.capito.senate.gov/contact/contact-shelley")
Rep.create(first_name: "Benjamin L.", first_three: "Ben", last_name: "Cardin", url: "http://www.cardin.senate.gov/contact/")
Rep.create(first_name: "Thomas R.", first_three: "Tho", last_name: "Carper", url: "http://www.carper.senate.gov/public/index.cfm/email-senator-carper")
Rep.create(first_name: "Robert P., Jr.", first_three: "Rob", last_name: "Casey", url: "http://www.casey.senate.gov/contact/")
Rep.create(first_name: "Bill", first_three: "Bil", last_name: "Cassidy", url: "http://www.cassidy.senate.gov/contact")
Rep.create(first_name: "Thad", first_three: "Tha", last_name: "Cochran", url: "http://www.cochran.senate.gov/public/index.cfm/email-me")
Rep.create(first_name: "Susan M.", first_three: "Sus", last_name: "Collins", url: "http://www.collins.senate.gov/contact")
Rep.create(first_name: "Christopher A.", first_three: "Chr", last_name: "Coons", url: "http://www.coons.senate.gov/contact")
Rep.create(first_name: "Bob", first_three: "Bob", last_name: "Corker", url: "http://www.corker.senate.gov/public/index.cfm/emailme")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Cornyn", url: "http://www.cornyn.senate.gov/contact")
Rep.create(first_name: "Catherine", first_three: "Cat", last_name: "Cortez Masto", url: "http://www.cortezmasto.senate.gov/content/contact-senator")
Rep.create(first_name: "Tom", first_three: "Tom", last_name: "Cotton", url: "http://www.cotton.senate.gov/?p=contact")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Crapo", url: "http://www.crapo.senate.gov/contact/email.cfm")
Rep.create(first_name: "Ted", first_three: "Ted", last_name: "Cruz", url: "http://www.cruz.senate.gov/?p=email_senator")
Rep.create(first_name: "Steve", first_three: "Ste", last_name: "Daines", url: "http://www.daines.senate.gov/connect/email-steve")
Rep.create(first_name: "Joe", first_three: "Joe", last_name: "Donnelly", url: "http://www.donnelly.senate.gov/contact/email-joe")
Rep.create(first_name: "Tammy", first_three: "Tam", last_name: "Duckworth", url: "http://www.duckworth.senate.gov/content/contact-senator")
Rep.create(first_name: "Richard J.", first_three: "Ric", last_name: "Durbin", url: "http://www.durbin.senate.gov/contact/")
Rep.create(first_name: "Michael B.", first_three: "Mic", last_name: "Enzi", url: "http://http://www.enzi.senate.gov/public/index.cfm/e-mail-senator-enzi")
Rep.create(first_name: "Joni", first_three: "Jon", last_name: "Ernst", url: "http://www.ernst.senate.gov/public/index.cfm/contact")
Rep.create(first_name: "Dianne", first_three: "Dia", last_name: "Feinstein", url: "http://www.feinstein.senate.gov/public/index.cfm/e-mail-me")
Rep.create(first_name: "Deb", first_three: "Deb", last_name: "Fischer", url: "http://www.fischer.senate.gov/public/index.cfm/contact")
Rep.create(first_name: "Jeff", first_three: "Jef", last_name: "Flake", url: "http://www.flake.senate.gov/public/index.cfm/contact-jeff")
Rep.create(first_name: "Al", first_three: "Al ", last_name: "Franken", url: "http://www.franken.senate.gov/?p=contact")
Rep.create(first_name: "Cory", first_three: "Cor", last_name: "Gardner", url: "http://www.gardner.senate.gov/contact-cory/email-cory")
Rep.create(first_name: "Kirsten E.", first_three: "Kir", last_name: "Gillibrand", url: "http://www.gillibrand.senate.gov/contact/")
Rep.create(first_name: "Lindsey", first_three: "Lin", last_name: "Graham", url: "https://http://www.lgraham.senate.gov/public/index.cfm/e-mail-senator-graham")
Rep.create(first_name: "Chuck", first_three: "Chu", last_name: "Grassley", url: "http://www.grassley.senate.gov/contact")
Rep.create(first_name: "Kamala D.", first_three: "Kam", last_name: "Harris", url: "http://www.harris.senate.gov/content/contact-senator")
Rep.create(first_name: "Margaret Wood", first_three: "Mar", last_name: "Hassan", url: "http://www.hassan.senate.gov/content/contact-senator")
Rep.create(first_name: "Orrin G.", first_three: "Orr", last_name: "Hatch", url: "http://www.hatch.senate.gov/public/index.cfm/contact?p=Email-Orrin")
Rep.create(first_name: "Martin", first_three: "Mar", last_name: "Heinrich", url: "http://www.heinrich.senate.gov/contact")
Rep.create(first_name: "Heidi", first_three: "Hei", last_name: "Heitkamp", url: "http://www.heitkamp.senate.gov/public/index.cfm/contact")
Rep.create(first_name: "Dean", first_three: "Dea", last_name: "Heller", url: "http://www.heller.senate.gov/public/index.cfm/contact-form")
Rep.create(first_name: "Mazie K.", first_three: "Maz", last_name: "Hirono", url: "http://www.hirono.senate.gov/contact")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Hoeven", url: "http://www.hoeven.senate.gov/public/index.cfm/email-the-senator")
Rep.create(first_name: "James M.", first_three: "Jam", last_name: "Inhofe", url: "http://www.inhofe.senate.gov/contact")
Rep.create(first_name: "Johnny", first_three: "Joh", last_name: "Isakson", url: "http://www.isakson.senate.gov/public/index.cfm/email-me")
Rep.create(first_name: "Ron", first_three: "Ron", last_name: "Johnson", url: "https://http://www.ronjohnson.senate.gov/public/index.cfm/email-the-senator")
Rep.create(first_name: "Tim", first_three: "Tim", last_name: "Kaine", url: "http://www.kaine.senate.gov/contact")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Kennedy", url: "http://www.kennedy.senate.gov/content/contact-senator")
Rep.create(first_name: "Angus S., Jr.", first_three: "Ang", last_name: "King", url: "http://www.king.senate.gov/contact")
Rep.create(first_name: "Amy", first_three: "Amy", last_name: "Klobuchar", url: "http://www.klobuchar.senate.gov/public/index.cfm/contact")
Rep.create(first_name: "James", first_three: "Jam", last_name: "Lankford", url: "http://www.lankford.senate.gov/contact/email")
Rep.create(first_name: "Patrick J.", first_three: "Pat", last_name: "Leahy", url: "http://www.leahy.senate.gov/contact/")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Lee", url: "http://www.lee.senate.gov/public/index.cfm/contact")
Rep.create(first_name: "Joe, III", first_three: "Joe", last_name: "Manchin", url: "http://www.manchin.senate.gov/public/index.cfm/contact-form")
Rep.create(first_name: "Edward J.", first_three: "Edw", last_name: "Markey", url: "http://www.markey.senate.gov/contact")
Rep.create(first_name: "John", first_three: "Joh", last_name: "McCain", url: "http://www.mccain.senate.gov/public/index.cfm/contact-form")
Rep.create(first_name: "Claire", first_three: "Cla", last_name: "McCaskill", url: "http://www.mccaskill.senate.gov/contact")
Rep.create(first_name: "Mitch", first_three: "Mit", last_name: "McConnell", url: "http://www.mcconnell.senate.gov/public/index.cfm?p=contact")
Rep.create(first_name: "Robert", first_three: "Rob", last_name: "Menendez", url: "http://www.menendez.senate.gov/contact")
Rep.create(first_name: "Jeff", first_three: "Jef", last_name: "Merkley", url: "http://www.merkley.senate.gov/contact/")
Rep.create(first_name: "Jerry", first_three: "Jer", last_name: "Moran", url: "http://www.moran.senate.gov/public/index.cfm/e-mail-jerry")
Rep.create(first_name: "Lisa", first_three: "Lis", last_name: "Murkowski", url: "http://www.murkowski.senate.gov/public/index.cfm/contact")
Rep.create(first_name: "Christopher", first_three: "Chr", last_name: "Murphy", url: "http://www.murphy.senate.gov/contact")
Rep.create(first_name: "Patty", first_three: "Pat", last_name: "Murray", url: "http://www.murray.senate.gov/public/index.cfm/contactme")
Rep.create(first_name: "Bill", first_three: "Bil", last_name: "Nelson", url: "http://www.billnelson.senate.gov/contact-bill")
Rep.create(first_name: "Rand", first_three: "Ran", last_name: "Paul", url: "http://www.paul.senate.gov/connect/email-rand")
Rep.create(first_name: "David", first_three: "Dav", last_name: "Perdue", url: "http://www.perdue.senate.gov/connect/email")
Rep.create(first_name: "Gary C.", first_three: "Gar", last_name: "Peters", url: "http://www.peters.senate.gov/contact/email-gary")
Rep.create(first_name: "Rob", first_three: "Rob", last_name: "Portman", url: "https://http://www.portman.senate.gov/public/index.cfm/contact-form")
Rep.create(first_name: "Jack", first_three: "Jac", last_name: "Reed", url: "http://www.reed.senate.gov/contact/")
Rep.create(first_name: "James E.", first_three: "Jam", last_name: "Risch", url: "http://www.risch.senate.gov/public/index.cfm?p=Email")
Rep.create(first_name: "Pat", first_three: "Pat", last_name: "Roberts", url: "http://www.roberts.senate.gov/public/?p=EmailPat")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Rounds", url: "http://www.rounds.senate.gov/contact/email-mike")
Rep.create(first_name: "Marco", first_three: "Mar", last_name: "Rubio", url: "http://www.rubio.senate.gov/public/index.cfm/contact")
Rep.create(first_name: "Bernard", first_three: "Ber", last_name: "Sanders", url: "http://www.sanders.senate.gov/contact/")
Rep.create(first_name: "Ben", first_three: "Ben", last_name: "Sasse", url: "http://www.sasse.senate.gov/public/index.cfm/email-ben")
Rep.create(first_name: "Brian", first_three: "Bri", last_name: "Schatz", url: "http://www.schatz.senate.gov/contact")
Rep.create(first_name: "Charles E.", first_three: "Cha", last_name: "Schumer", url: "http://www.schumer.senate.gov/contact/email-chuck")
Rep.create(first_name: "Tim", first_three: "Tim", last_name: "Scott", url: "http://www.scott.senate.gov/contact/email-me")
Rep.create(first_name: "Jeanne", first_three: "Jea", last_name: "Shaheen", url: "http://www.shaheen.senate.gov/contact/contact-jeanne")
Rep.create(first_name: "Richard C.", first_three: "Ric", last_name: "Shelby", url: "http://www.shelby.senate.gov/public/index.cfm/emailsenatorshelby")
Rep.create(first_name: "Debbie", first_three: "Deb", last_name: "Stabenow", url: "http://www.stabenow.senate.gov/?p=contact")
Rep.create(first_name: "Dan", first_three: "Dan", last_name: "Sullivan", url: "http://www.sullivan.senate.gov/contact/email")
Rep.create(first_name: "Jon", first_three: "Jon", last_name: "Tester", url: "http://www.tester.senate.gov/?p=email_senator")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Thune", url: "http://www.thune.senate.gov/public/index.cfm/contact")
Rep.create(first_name: "Thom", first_three: "Tho", last_name: "Tillis", url: "http://www.tillis.senate.gov/public/index.cfm/email-me")
Rep.create(first_name: "Patrick J.", first_three: "Pat", last_name: "Toomey", url: "http://www.toomey.senate.gov/?p=contact")
Rep.create(first_name: "Tom", first_three: "Tom", last_name: "Udall", url: "http://www.tomudall.senate.gov/?p=contact")
Rep.create(first_name: "Chris", first_three: "Chr", last_name: "Van Hollen", url: "http://www.vanhollen.senate.gov/content/contact-senator")
Rep.create(first_name: "Mark R.", first_three: "Mar", last_name: "Warner", url: "http://www.warner.senate.gov/public/index.cfm?p=Contact")
Rep.create(first_name: "Elizabeth", first_three: "Eli", last_name: "Warren", url: "http://www.warren.senate.gov/?p=email_senator")
Rep.create(first_name: "Sheldon", first_three: "She", last_name: "Whitehouse", url: "http://www.whitehouse.senate.gov/contact/email-sheldon")
Rep.create(first_name: "Roger F.", first_three: "Rog", last_name: "Wicker", url: "http://www.wicker.senate.gov/public/index.cfm/contact")
Rep.create(first_name: "Ron", first_three: "Ron", last_name: "Wyden", url: "http://www.wyden.senate.gov/contact/")
Rep.create(first_name: "Todd", first_three: "Tod", last_name: "Young", url: "http://www.young.senate.gov/content/contact-senator")
Rep.create(first_name: "Ralph", first_three: "Ral", last_name: "Abraham", url: "http://Abraham.house.gov/contact/email")
Rep.create(first_name: "Pete", first_three: "Pet", last_name: "Aguilar", url: "http://Aguilar.house.gov/contact/email")
Rep.create(first_name: "Rick", first_three: "Ric", last_name: "Allen", url: "http://Allen.house.gov/contact/email")
Rep.create(first_name: "Jodey", first_three: "Jod", last_name: "Arrington", url: "http://Arrington.house.gov/contact/email")
Rep.create(first_name: "Austin", first_three: "Aus", last_name: "Scott", url: "http://AustinScott.house.gov/contact/email")
Rep.create(first_name: "Brian", first_three: "Bri", last_name: "Babin", url: "http://Babin.house.gov/contact/email")
Rep.create(first_name: "Don", first_three: "Don", last_name: "Bacon", url: "http://Bacon.house.gov/contact/email")
Rep.create(first_name: "Jim", first_three: "Jim", last_name: "Banks", url: "http://Banks.house.gov/contact/email")
Rep.create(first_name: "Joe", first_three: "Joe", last_name: "Barton", url: "http://Barton.house.gov/contact/email")
Rep.create(first_name: "Karen", first_three: "Kar", last_name: "Bass", url: "http://Bass.house.gov/contact/email")
Rep.create(first_name: "Bennie", first_three: "Ben", last_name: "Thompson", url: "http://BennieThompson.house.gov/contact/email")
Rep.create(first_name: "Jack", first_three: "Jac", last_name: "Bergman", url: "http://Bergman.house.gov/contact/email")
Rep.create(first_name: "Don", first_three: "Don", last_name: "Beyer", url: "http://Beyer.house.gov/contact/email")
Rep.create(first_name: "Andy", first_three: "And", last_name: "Biggs", url: "http://Biggs.house.gov/contact/email")
Rep.create(first_name: "Bill", first_three: "Bil", last_name: "Johnson", url: "http://BillJohnson.house.gov/contact/email")
Rep.create(first_name: "Marsha", first_three: "Mar", last_name: "Blackburn", url: "http://Blackburn.house.gov/contact/email")
Rep.create(first_name: "Rod", first_three: "Rod", last_name: "Blum", url: "http://Blum.house.gov/contact/email")
Rep.create(first_name: "Earl", first_three: "Ear", last_name: "Blumenauer", url: "http://Blumenauer.house.gov/contact/email")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Bost", url: "http://Bost.house.gov/contact/email")
Rep.create(first_name: "Brendan", first_three: "Bre", last_name: "Boyle", url: "http://Boyle.house.gov/contact/email")
Rep.create(first_name: "Dave", first_three: "Dav", last_name: "Brat", url: "http://Brat.house.gov/contact/email")
Rep.create(first_name: "Jim", first_three: "Jim", last_name: "Bridenstine", url: "http://Bridenstine.house.gov/contact/email")
Rep.create(first_name: "Julia", first_three: "Jul", last_name: "Brownley", url: "http://Brownley.house.gov/contact/email")
Rep.create(first_name: "Ken", first_three: "Ken", last_name: "Buck", url: "http://Buck.house.gov/contact/email")
Rep.create(first_name: "Larry", first_three: "Lar", last_name: "Bucshon", url: "http://Bucshon.house.gov/contact/email")
Rep.create(first_name: "Ted", first_three: "Ted", last_name: "Budd", url: "http://Budd.house.gov/contact/email")
Rep.create(first_name: "Buddy", first_three: "Bud", last_name: "Carter", url: "http://BuddyCarter.house.gov/contact/email")
Rep.create(first_name: "Michael", first_three: "Mic", last_name: "Burgess", url: "http://Burgess.house.gov/contact/email")
Rep.create(first_name: "Ken", first_three: "Ken", last_name: "Calvert", url: "http://Calvert.house.gov/contact/email")
Rep.create(first_name: "Salud", first_three: "Sal", last_name: "Carbajal", url: "http://Carbajal.house.gov/contact/email")
Rep.create(first_name: "Kathy", first_three: "Kat", last_name: "Castor", url: "http://Castor.house.gov/contact/email")
Rep.create(first_name: "Steve", first_three: "Ste", last_name: "Chabot", url: "http://Chabot.house.gov/contact/email")
Rep.create(first_name: "Jason", first_three: "Jas", last_name: "Chaffetz", url: "http://Chaffetz.house.gov/contact/email")
Rep.create(first_name: "Liz", first_three: "Liz", last_name: "Cheney", url: "http://Cheney.house.gov/contact/email")
Rep.create(first_name: "Chris", first_three: "Chr", last_name: "Collins", url: "http://ChrisCollins.house.gov/contact/email")
Rep.create(first_name: "Chris", first_three: "Chr", last_name: "Smith", url: "http://ChrisSmith.house.gov/contact/email")
Rep.create(first_name: "Judy", first_three: "Jud", last_name: "Chu", url: "http://Chu.house.gov/contact/email")
Rep.create(first_name: "Yvette", first_three: "Yve", last_name: "Clarke", url: "http://Clarke.house.gov/contact/email")
Rep.create(first_name: "Lacy", first_three: "Lac", last_name: "Clay", url: "http://Clay.house.gov/contact/email")
Rep.create(first_name: "Clay", first_three: "Cla", last_name: "Higgins", url: "http://ClayHiggins.house.gov/contact/email")
Rep.create(first_name: "Steve", first_three: "Ste", last_name: "Cohen", url: "http://Cohen.house.gov/contact/email")
Rep.create(first_name: "Tom", first_three: "Tom", last_name: "Cole", url: "http://Cole.house.gov/contact/email")
Rep.create(first_name: "James", first_three: "Jam", last_name: "Comer", url: "http://Comer.house.gov/contact/email")
Rep.create(first_name: "Barbara", first_three: "Bar", last_name: "Comstock", url: "http://Comstock.house.gov/contact/email")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Conaway", url: "http://Conaway.house.gov/contact/email")
Rep.create(first_name: "Gerry", first_three: "Ger", last_name: "Connolly", url: "http://Connolly.house.gov/contact/email")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Conyers", url: "http://Conyers.house.gov/contact/email")
Rep.create(first_name: "Lou", first_three: "Lou", last_name: "Correa", url: "http://Correa.house.gov/contact/email")
Rep.create(first_name: "Ryan", first_three: "Rya", last_name: "Costello", url: "http://Costello.house.gov/contact/email")
Rep.create(first_name: "Joe", first_three: "Joe", last_name: "Courtney", url: "http://Courtney.house.gov/contact/email")
Rep.create(first_name: "Rick", first_three: "Ric", last_name: "Crawford", url: "http://Crawford.house.gov/contact/email")
Rep.create(first_name: "Charlie", first_three: "Cha", last_name: "Crist", url: "http://Crist.house.gov/contact/email")
Rep.create(first_name: "Henry", first_three: "Hen", last_name: "Cuellar", url: "http://Cuellar.house.gov/contact/email")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Culberson", url: "http://Culberson.house.gov/contact/email")
Rep.create(first_name: "Elijah", first_three: "Eli", last_name: "Cummings", url: "http://Cummings.house.gov/contact/email")
Rep.create(first_name: "Carlos", first_three: "Car", last_name: "Curbelo", url: "http://Curbelo.house.gov/contact/email")
Rep.create(first_name: "David", first_three: "Dav", last_name: "Scott", url: "http://DavidScott.house.gov/contact/email")
Rep.create(first_name: "Warren", first_three: "War", last_name: "Davidson", url: "http://Davidson.house.gov/contact/email")
Rep.create(first_name: "David", first_three: "Dav", last_name: "Young", url: "http://DavidYoung.house.gov/contact/email")
Rep.create(first_name: "Rosa", first_three: "Ros", last_name: "DeLauro", url: "http://DeLauro.house.gov/contact/email")
Rep.create(first_name: "Val", first_three: "Val", last_name: "Demings", url: "http://Demings.house.gov/contact/email")
Rep.create(first_name: "Jeff", first_three: "Jef", last_name: "Denham", url: "http://Denham.house.gov/contact/email")
Rep.create(first_name: "Mark", first_three: "Mar", last_name: "DeSaulnier", url: "http://DeSaulnier.house.gov/contact/email")
Rep.create(first_name: "Ted", first_three: "Ted", last_name: "Deutch", url: "http://Deutch.house.gov/contact/email")
Rep.create(first_name: "Lloyd", first_three: "Llo", last_name: "Doggett", url: "http://Doggett.house.gov/contact/email")
Rep.create(first_name: "Dan", first_three: "Dan", last_name: "Donovan", url: "http://Donovan.house.gov/contact/email")
Rep.create(first_name: "Don", first_three: "Don", last_name: "Young", url: "http://DonYoung.house.gov/contact/email")
Rep.create(first_name: "Neal", first_three: "Nea", last_name: "Dunn", url: "http://Dunn.house.gov/contact/email")
Rep.create(first_name: "Tom", first_three: "Tom", last_name: "Emmer", url: "http://Emmer.house.gov/contact/email")
Rep.create(first_name: "Anna", first_three: "Ann", last_name: "Eshoo", url: "http://Eshoo.house.gov/contact/email")
Rep.create(first_name: "Adriano", first_three: "Adr", last_name: "Espaillat", url: "http://Espaillat.house.gov/contact/email")
Rep.create(first_name: "Elizabeth", first_three: "Eli", last_name: "Esty", url: "http://Esty.house.gov/contact/email")
Rep.create(first_name: "Evan", first_three: "Eva", last_name: "Jenkins", url: "http://EvanJenkins.house.gov/contact/email")
Rep.create(first_name: "Dwight", first_three: "Dwi", last_name: "Evans", url: "http://Evans.house.gov/contact/email")
Rep.create(first_name: "Blake", first_three: "Bla", last_name: "Farenthold", url: "http://Farenthold.house.gov/contact/email")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Faso", url: "http://Faso.house.gov/contact/email")
Rep.create(first_name: "Drew", first_three: "Dre", last_name: "Ferguson", url: "http://Ferguson.house.gov/contact/email")
Rep.create(first_name: "Brian", first_three: "Bri", last_name: "Fitzpatrick", url: "http://Fitzpatrick.house.gov/contact/email")
Rep.create(first_name: "Bill", first_three: "Bil", last_name: "Flores", url: "http://Flores.house.gov/contact/email")
Rep.create(first_name: "Virginia", first_three: "Vir", last_name: "Foxx", url: "http://Foxx.house.gov/contact/email")
Rep.create(first_name: "Francis", first_three: "Fra", last_name: "Rooney", url: "http://FrancisRooney.house.gov/contact/email")
Rep.create(first_name: "Lois", first_three: "Loi", last_name: "Frankel", url: "http://Frankel.house.gov/contact/email")
Rep.create(first_name: "Trent", first_three: "Tre", last_name: "Franks", url: "http://Franks.house.gov/contact/email")
Rep.create(first_name: "Matt", first_three: "Mat", last_name: "Gaetz", url: "http://Gaetz.house.gov/contact/email")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Gallagher", url: "http://Gallagher.house.gov/contact/email")
Rep.create(first_name: "Bob", first_three: "Bob", last_name: "Gibbs", url: "http://Gibbs.house.gov/contact/email")
Rep.create(first_name: "Louie", first_three: "Lou", last_name: "Gohmert", url: "http://Gohmert.house.gov/contact/email")
Rep.create(first_name: "Bob", first_three: "Bob", last_name: "Goodlatte", url: "http://Goodlatte.house.gov/contact/email")
Rep.create(first_name: "Josh", first_three: "Jos", last_name: "Gottheimer", url: "http://Gottheimer.house.gov/contact/email")
Rep.create(first_name: "Gene", first_three: "Gen", last_name: "Green", url: "http://Green.house.gov/contact/email")
Rep.create(first_name: "Morgan", first_three: "Mor", last_name: "Griffith", url: "http://Griffith.house.gov/contact/email")
Rep.create(first_name: "Glenn", first_three: "Gle", last_name: "Grothman", url: "http://Grothman.house.gov/contact/email")
Rep.create(first_name: "Colleen", first_three: "Col", last_name: "Hanabusa", url: "http://Hanabusa.house.gov/contact/email")
Rep.create(first_name: "Hank", first_three: "Han", last_name: "Johnson", url: "http://HankJohnson.house.gov/contact/email")
Rep.create(first_name: "Vicky", first_three: "Vic", last_name: "Hartzler", url: "http://Hartzler.house.gov/contact/email")
Rep.create(first_name: "Jaime", first_three: "Jai", last_name: "Herrera Beutler ", url: "http://herrerabeutler.house.gov/contact/")
Rep.create(first_name: "Jody", first_three: "Jod", last_name: "Hice", url: "http://Hice.house.gov/contact/email")
Rep.create(first_name: "Brian", first_three: "Bri", last_name: "Higgins", url: "https://higginsforms.house.gov/contact/")
Rep.create(first_name: "French", first_three: "Fre", last_name: "Hill", url: "http://Hill.house.gov/contact/email")
Rep.create(first_name: "George", first_three: "Geo", last_name: "Holding", url: "http://Holding.house.gov/contact/email")
Rep.create(first_name: "Trey", first_three: "Tre", last_name: "Hollingsworth", url: "http://Hollingsworth.house.gov/contact/email")
Rep.create(first_name: "Bill", first_three: "Bil", last_name: "Huizenga", url: "http://Huizenga.house.gov/contact/email")
Rep.create(first_name: "Will", first_three: "Wil", last_name: "Hurd", url: "http://Hurd.house.gov/contact/email")
Rep.create(first_name: "Jason", first_three: "Jas", last_name: "Lewis", url: "http://JasonLewis.house.gov/contact/email")
Rep.create(first_name: "Pramila", first_three: "Pra", last_name: "Jayapal", url: "http://Jayapal.house.gov/contact/email")
Rep.create(first_name: "Jim", first_three: "Jim", last_name: "Jordan", url: "http://Jordan.house.gov/contact/email")
Rep.create(first_name: "Marcy", first_three: "Mar", last_name: "Kaptur", url: "http://Kaptur.house.gov/contact/email")
Rep.create(first_name: "Kathleen", first_three: "Kat", last_name: "Rice", url: "http://KathleenRice.house.gov/contact/email")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Katko", url: "http://Katko.house.gov/contact/email")
Rep.create(first_name: "Bill", first_three: "Bil", last_name: "Keating", url: "http://Keating.house.gov/contact/email")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Kelly", url: "https://kelly.house.gov/contact-me/email-me")
Rep.create(first_name: "Kevin", first_three: "Kev", last_name: "Brady", url: "http://KevinBrady.house.gov/contact/email")
Rep.create(first_name: "Ro", first_three: "Ro", last_name: "Khanna", url: "http://Khanna.house.gov/contact/email")
Rep.create(first_name: "Ruben", first_three: "Rub", last_name: "Kihuen", url: "http://Kihuen.house.gov/contact/email")
Rep.create(first_name: "Dan", first_three: "Dan", last_name: "Kildee", url: "http://Kildee.house.gov/contact/email")
Rep.create(first_name: "Ron", first_three: "Ron", last_name: "Kind", url: "http://Kind.house.gov/contact/email")
Rep.create(first_name: "Adam", first_three: "Ada", last_name: "Kinzinger", url: "http://Kinzinger.house.gov/contact/email")
Rep.create(first_name: "Steve", first_three: "Ste", last_name: "Knight", url: "http://Knight.house.gov/contact/email")
Rep.create(first_name: "Raja", first_three: "Raj", last_name: "Krishnamoorthi", url: "http://Krishnamoorthi.house.gov/contact/email")
Rep.create(first_name: "David", first_three: "Dav", last_name: "Kustoff", url: "http://Kustoff.house.gov/contact/email")
Rep.create(first_name: "Darin", first_three: "Dar", last_name: "LaHood", url: "http://LaHood.house.gov/contact/email")
Rep.create(first_name: "Doug", first_three: "Dou", last_name: "Lamborn", url: "http://Lamborn.house.gov/contact/email")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Larson", url: "http://Larson.house.gov/contact/email")
Rep.create(first_name: "Bob", first_three: "Bob", last_name: "Latta", url: "http://Latta.house.gov/contact/email")
Rep.create(first_name: "Brenda", first_three: "Bre", last_name: "Lawrence", url: "http://Lawrence.house.gov/contact/email")
Rep.create(first_name: "Al", first_three: "Al", last_name: "Lawson", url: "http://Lawson.house.gov/contact/email")
Rep.create(first_name: "Ted", first_three: "Ted", last_name: "Lieu", url: "http://Lieu.house.gov/contact/email")
Rep.create(first_name: "Dave", first_three: "Dav", last_name: "Loebsack", url: "http://Loebsack.house.gov/contact/email")
Rep.create(first_name: "Zoe", first_three: "Zoe", last_name: "Lofgren", url: "http://Lofgren.house.gov/contact/email")
Rep.create(first_name: "Barry", first_three: "Bar", last_name: "Loudermilk", url: "http://Loudermilk.house.gov/contact/email")
Rep.create(first_name: "Alan", first_three: "Ala", last_name: "Lowenthal", url: "http://Lowenthal.house.gov/contact/email")
Rep.create(first_name: "Nita", first_three: "Nit", last_name: "Lowey", url: "http://Lowey.house.gov/contact/email")
Rep.create(first_name: "Blaine", first_three: "Bla", last_name: "Luetkemeyer", url: "http://Luetkemeyer.house.gov/contact/email")
Rep.create(first_name: "Tom", first_three: "Tom", last_name: "MacArthur", url: "http://MacArthur.house.gov/contact/email")
Rep.create(first_name: "Carolyn", first_three: "Car", last_name: "Maloney", url: "http://maloney.house.gov/services/email-me")
Rep.create(first_name: "Kenny", first_three: "Ken", last_name: "Marchant", url: "http://Marchant.house.gov/contact/email")
Rep.create(first_name: "Tom", first_three: "Tom", last_name: "Marino", url: "http://Marino.house.gov/contact/email")
Rep.create(first_name: "Roger", first_three: "Rog", last_name: "Marshall", url: "http://Marshall.house.gov/contact/email")
Rep.create(first_name: "Brian", first_three: "Bri", last_name: "Mast", url: "http://Mast.house.gov/contact/email")
Rep.create(first_name: "Doris", first_three: "Dor", last_name: "Matsui", url: "http://matsui.house.gov/how-can-i-help/email-doris/")
Rep.create(first_name: "Donald", first_three: "Don", last_name: "McEachin", url: "http://McEachin.house.gov/contact/email")
Rep.create(first_name: "Patrick", first_three: "Pat", last_name: "McHenry", url: "http://McHenry.house.gov/contact/email")
Rep.create(first_name: "Martha", first_three: "Mar", last_name: "McSally", url: "http://McSally.house.gov/contact/email")
Rep.create(first_name: "Luke", first_three: "Luk", last_name: "Messer", url: "http://Messer.house.gov/contact/email")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Bishop", url: "http://MikeBishop.house.gov/contact/email")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Johnson", url: "http://MikeJohnson.house.gov/contact/email")
Rep.create(first_name: "Paul", first_three: "Pau", last_name: "Mitchell", url: "http://Mitchell.house.gov/contact/email")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Moolenaar", url: "http://Moolenaar.house.gov/contact/email")
Rep.create(first_name: "Alex", first_three: "Ale", last_name: "Mooney", url: "http://Mooney.house.gov/contact/email")
Rep.create(first_name: "Seth", first_three: "Set", last_name: "Moulton", url: "http://Moulton.house.gov/contact/email")
Rep.create(first_name: "Markwayne", first_three: "Mar", last_name: "Mullin", url: "http://Mullin.house.gov/contact/email")
Rep.create(first_name: "Timothy", first_three: "Tim", last_name: "Murphy", url: "http://Murphy.house.gov/contact/email")
Rep.create(first_name: "Richard", first_three: "Ric", last_name: "Neal", url: "http://Neal.house.gov/contact/email")
Rep.create(first_name: "Dan", first_three: "Dan", last_name: "Newhouse", url: "http://Newhouse.house.gov/contact/email")
Rep.create(first_name: "Devin", first_three: "Dev", last_name: "Nunes", url: "http://Nunes.house.gov/contact/email")
Rep.create(first_name: "Tom", first_three: "Tom", last_name: "OHalleran", url: "http://OHalleran.house.gov/contact/email")
Rep.create(first_name: "Steven", first_three: "Ste", last_name: "Palazzo", url: "http://Palazzo.house.gov/contact/email")
Rep.create(first_name: "Gary", first_three: "Gar", last_name: "Palmer", url: "http://Palmer.house.gov/contact/email")
Rep.create(first_name: "Jimmy", first_three: "Jim", last_name: "Panetta", url: "http://Panetta.house.gov/contact/email")
Rep.create(first_name: "Paul", first_three: "Pau", last_name: "Ryan", url: "http://PaulRyan.house.gov/contact/email")
Rep.create(first_name: "Ed", first_three: "Ed", last_name: "Perlmutter", url: "http://Perlmutter.house.gov/contact/email")
Rep.create(first_name: "Scott", first_three: "Sco", last_name: "Perry", url: "http://Perry.house.gov/contact/email")
Rep.create(first_name: "Peter", first_three: "Pet", last_name: "King", url: "https://peteking.house.gov/contact/email-me")
Rep.create(first_name: "Bruce", first_three: "Bru", last_name: "Poliquin", url: "http://Poliquin.house.gov/contact/email")
Rep.create(first_name: "Jared", first_three: "Jar", last_name: "Polis", url: "http://Polis.house.gov/contact/email")
Rep.create(first_name: "Bill", first_three: "Bil", last_name: "Posey", url: "http://Posey.house.gov/contact/email")
Rep.create(first_name: "Jamie", first_three: "Jam", last_name: "Raskin", url: "http://Raskin.house.gov/contact/email")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Ratcliffe", url: "http://Ratcliffe.house.gov/contact/email")
Rep.create(first_name: "Tom", first_three: "Tom", last_name: "Reed", url: "http://Reed.house.gov/contact/email")
Rep.create(first_name: "Rob", first_three: "Rob", last_name: "Bishop", url: "http://RobBishop.house.gov/contact/email")
Rep.create(first_name: "Rodney", first_three: "Rod", last_name: "Davis", url: "http://RodneyDavis.house.gov/contact/email")
Rep.create(first_name: "Phil", first_three: "Phi", last_name: "Roe", url: "http://Roe.house.gov/contact/email")
Rep.create(first_name: "Tom", first_three: "Tom", last_name: "Rooney", url: "http://Rooney.house.gov/contact/email")
Rep.create(first_name: "Jacky", first_three: "Jac", last_name: "Rosen", url: "http://Rosen.house.gov/contact/email")
Rep.create(first_name: "David", first_three: "Dav", last_name: "Rouzer", url: "http://Rouzer.house.gov/contact/email")
Rep.create(first_name: "Lucille", first_three: "Luc", last_name: "Roybal-Allard", url: "http://Roybal-Allard.house.gov/contact/email")
Rep.create(first_name: "Raul", first_three: "Rau", last_name: "Ruiz", url: "http://Ruiz.house.gov/contact/email")
Rep.create(first_name: "Steve", first_three: "Ste", last_name: "Russell", url: "http://Russell.house.gov/contact/email")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Rutherford", url: "http://Rutherford.house.gov/contact/email")
Rep.create(first_name: "Sam", first_three: "Sam", last_name: "Johnson", url: "http://SamJohnson.house.gov/contact/email")
Rep.create(first_name: "Brad", first_three: "Bra", last_name: "Schneider", url: "http://Schneider.house.gov/contact/email")
Rep.create(first_name: "Kurt", first_three: "Kur", last_name: "Schrader", url: "http://Schrader.house.gov/contact/email")
Rep.create(first_name: "David", first_three: "Dav", last_name: "Schweikert", url: "http://Schweikert.house.gov/contact/email")
Rep.create(first_name: "Jim", first_three: "Jim", last_name: "Sensenbrenner", url: "http://Sensenbrenner.house.gov/contact/email")
Rep.create(first_name: "Pete", first_three: "Pet", last_name: "Sessions", url: "http://Sessions.house.gov/contact/email")
Rep.create(first_name: "Carol", first_three: "Car", last_name: "Shea-Porter", url: "http://Shea-Porter.house.gov/contact/email")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Simpson", url: "http://Simpson.house.gov/contact/email")
Rep.create(first_name: "Albio", first_three: "Alb", last_name: "Sires", url: "http://Sires.house.gov/contact/email")
Rep.create(first_name: "Lloyd", first_three: "Llo", last_name: "Smucker", url: "http://Smucker.house.gov/contact/email")
Rep.create(first_name: "Darren", first_three: "Dar", last_name: "Soto", url: "http://Soto.house.gov/contact/email")
Rep.create(first_name: "Jackie", first_three: "Jac", last_name: "Speier", url: "http://Speier.house.gov/contact/email")
Rep.create(first_name: "Elise", first_three: "Eli", last_name: "Stefanik", url: "http://Stefanik.house.gov/contact/email")
Rep.create(first_name: "Stephanie", first_three: "Ste", last_name: "Murphy", url: "http://StephanieMurphy.house.gov/contact/email")
Rep.create(first_name: "Steve", first_three: "Ste", last_name: "Stivers", url: "http://Stivers.house.gov/contact/email")
Rep.create(first_name: "Thomas", first_three: "Tho", last_name: "Suozzi", url: "http://Suozzi.house.gov/contact/email")
Rep.create(first_name: "Eric", first_three: "Eri", last_name: "Swalwell", url: "http://Swalwell.house.gov/contact/email")
Rep.create(first_name: "Scott", first_three: "Sco", last_name: "Taylor", url: "http://Taylor.house.gov/contact/email")
Rep.create(first_name: "Claudia", first_three: "Cla", last_name: "Tenney", url: "http://Tenney.house.gov/contact/email")
Rep.create(first_name: "Glenn", first_three: "Gle", last_name: "Thompson", url: "https://thompson.house.gov/contact-me/email-me")
Rep.create(first_name: "Mac", first_three: "Mac", last_name: "Thornberry", url: "http://Thornberry.house.gov/contact/email")
Rep.create(first_name: "Pat", first_three: "Pat", last_name: "Tiberi", url: "http://Tiberi.house.gov/contact/email")
Rep.create(first_name: "Tom", first_three: "Tom", last_name: "Graves", url: "http://TomGraves.house.gov/contact/email")
Rep.create(first_name: "Tom", first_three: "Tom", last_name: "Rice", url: "http://tomriceforms.house.gov/contact/")
Rep.create(first_name: "Paul", first_three: "Pau", last_name: "Tonko", url: "http://Tonko.house.gov/contact/email")
Rep.create(first_name: "Norma", first_three: "Nor", last_name: "Torres", url: "http://Torres.house.gov/contact/email")
Rep.create(first_name: "Trent", first_three: "Tre", last_name: "Kelly", url: "http://TrentKelly.house.gov/contact/email")
Rep.create(first_name: "Dave", first_three: "Dav", last_name: "Trott", url: "http://Trott.house.gov/contact/email")
Rep.create(first_name: "Fred", first_three: "Fre", last_name: "Upton", url: "http://Upton.house.gov/contact/email")
Rep.create(first_name: "David", first_three: "Dav", last_name: "Valadao", url: "http://Valadao.house.gov/contact/email")
Rep.create(first_name: "Tim", first_three: "Tim", last_name: "Walberg", url: "http://Walberg.house.gov/contact/email")
Rep.create(first_name: "Mark", first_three: "Mar", last_name: "Walker", url: "http://Walker.house.gov/contact/email")
Rep.create(first_name: "Jackie", first_three: "Jac", last_name: "Walorski", url: "http://Walorski.house.gov/contact/email")
Rep.create(first_name: "Mimi", first_three: "Mim", last_name: "Walters", url: "http://Walters.house.gov/contact/email")
Rep.create(first_name: "Maxine", first_three: "Max", last_name: "Waters", url: "http://Waters.house.gov/contact/email")
Rep.create(first_name: "Daniel", first_three: "Dan", last_name: "Webster", url: "http://Webster.house.gov/contact/email")
Rep.create(first_name: "Peter", first_three: "Pet", last_name: "Welch", url: "http://Welch.house.gov/contact/email")
Rep.create(first_name: "Brad", first_three: "Bra", last_name: "Wenstrup", url: "http://Wenstrup.house.gov/contact/email")
Rep.create(first_name: "Bruce", first_three: "Bru", last_name: "Westerman", url: "http://Westerman.house.gov/contact/email")
Rep.create(first_name: "Frederica", first_three: "Fre", last_name: "Wilson", url: "http://wilson.house.gov/contact")
Rep.create(first_name: "Rob", first_three: "Rob", last_name: "Wittman", url: "http://Wittman.house.gov/contact/email")
Rep.create(first_name: "Steve", first_three: "Ste", last_name: "Womack", url: "http://Womack.house.gov/contact/email")
Rep.create(first_name: "Rob", first_three: "Rob", last_name: "Woodall", url: "http://Woodall.house.gov/contact/email")
Rep.create(first_name: "Lee", first_three: "Lee", last_name: "Zeldin", url: "http://Zeldin.house.gov/contact/email")
Rep.create(first_name: "Anthony", first_three: "Ant", last_name: "Brown  ", url: "https://anthonybrown.house.gov/contact/email")
Rep.create(first_name: "Lisa", first_three: "Lis", last_name: "Blunt Rochester ", url: "https://bluntrochester.house.gov/contact/")
Rep.create(first_name: "Eddie", first_three: "Edd", last_name: "Bernice Johnson ", url: "https://ebjohnson.house.gov/contact/email-me")
Rep.create(first_name: "Sheila", first_three: "She", last_name: "Jackson Lee ", url: "https://jacksonlee.house.gov/contact/email-me")
Rep.create(first_name: "Ann", first_three: "Ann", last_name: "McLane Kuster ", url: "https://kuster.house.gov/contact/email-me")
Rep.create(first_name: "Ben", first_three: "Ben", last_name: "Ray Lujan ", url: "https://lujan.house.gov/issue-subscribe")
Rep.create(first_name: "Michelle", first_three: "Mic", last_name: "Lujan Grisham ", url: "https://lujangrisham.house.gov/contact")
Rep.create(first_name: "Cathy", first_three: "Cat", last_name: "McMorris Rodgers ", url: "https://mcmorris.house.gov/contact/")
Rep.create(first_name: "Debbie", first_three: "Deb", last_name: "Wasserman Schultz ", url: "https://wassermanschultzforms.house.gov/contact/")
Rep.create(first_name: "Bonnie", first_three: "Bon", last_name: "Watson Coleman ", url: "https://watsoncoleman.house.gov/contact/email")
Rep.create(first_name: "Alma", first_three: "Alm", last_name: "Adams", url: "http://adamsforms.house.gov/contact")
Rep.create(first_name: "Robert", first_three: "Rob", last_name: "Aderholt", url: "https://aderholt.house.gov/contact/email-robert")
Rep.create(first_name: "Justin", first_three: "Jus", last_name: "Amash", url: "https://amash.house.gov/contact-me/email-me")
Rep.create(first_name: "Mark", first_three: "Mar", last_name: "Amodei", url: "https://amodei.house.gov/email-me/")
Rep.create(first_name: "Lou", first_three: "Lou", last_name: "Barletta", url: "https://barletta.house.gov/contact/email-me")
Rep.create(first_name: "Andy", first_three: "And", last_name: "Barr", url: "https://barr.house.gov/contact/email-me")
Rep.create(first_name: "Nanette", first_three: "Nan", last_name: "Barragan", url: "https://barragan.house.gov/contact/email")
Rep.create(first_name: "Joyce", first_three: "Joy", last_name: "Beatty", url: "https://beatty.house.gov/contact/email-me")
Rep.create(first_name: "Ami", first_three: "Ami", last_name: "Bera", url: "https://bera.house.gov/connect-with-me/email-ami")
Rep.create(first_name: "Gus", first_three: "Gus", last_name: "Bilirakis", url: "https://bilirakis.house.gov/contact/email-me")
Rep.create(first_name: "Diane", first_three: "Dia", last_name: "Black", url: "https://black.house.gov/contact-me/email-me")
Rep.create(first_name: "Suzanne", first_three: "Suz", last_name: "Bonamici", url: "https://bonamici.house.gov/contact-me/email-me")
Rep.create(first_name: "Vern", first_three: "Ver", last_name: "Buchanan", url: "https://buchanan.house.gov/contact/email-me")
Rep.create(first_name: "Cheri", first_three: "Che", last_name: "Bustos", url: "https://bustos.house.gov/contact/")
Rep.create(first_name: "G.", first_three: "G.", last_name: "Butterfield", url: "https://butterfield.house.gov/contact/email-me")
Rep.create(first_name: "Bradley", first_three: "Bra", last_name: "Byrne", url: "https://byrne.house.gov/contact/email-me")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Capuano", url: "http://capuano.house.gov/contact/email.shtml")
Rep.create(first_name: "Adam", first_three: "Ada", last_name: "Smith", url: "http://AdamSmith.house.gov/contact/email-me")
Rep.create(first_name: "Sanford", first_three: "San", last_name: "Bishop", url: "http://Bishop.house.gov/contact/email-me")
Rep.create(first_name: "Bobby", first_three: "Bob", last_name: "Scott", url: "http://BobbyScott.house.gov/contact/email-me")
Rep.create(first_name: "André", first_three: "And", last_name: "Carson", url: "http://Carson.house.gov/contact/email-me")
Rep.create(first_name: "Matt", first_three: "Mat", last_name: "Cartwright", url: "http://Cartwright.house.gov/contact/email-me")
Rep.create(first_name: "Joaquín", first_three: "Joa", last_name: "Castro", url: "http://Castro.house.gov/contact/email-me")
Rep.create(first_name: "Emanuel", first_three: "Ema", last_name: "Cleaver", url: "http://Cleaver.house.gov/contact/email-me")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Coffman", url: "http://Coffman.house.gov/contact/email-me")
Rep.create(first_name: "Paul", first_three: "Pau", last_name: "Cook", url: "http://Cook.house.gov/contact/email-me")
Rep.create(first_name: "Jim", first_three: "Jim", last_name: "Cooper", url: "http://Cooper.house.gov/contact/email-me")
Rep.create(first_name: "Jim", first_three: "Jim", last_name: "Costa", url: "http://Costa.house.gov/contact/email-me")
Rep.create(first_name: "Kevin", first_three: "Kev", last_name: "Cramer", url: "http://Cramer.house.gov/contact/email-me")
Rep.create(first_name: "Peter", first_three: "Pet", last_name: "DeFazio", url: "http://DeFazio.house.gov/contact/email-me")
Rep.create(first_name: "Diana", first_three: "Dia", last_name: "DeGette", url: "http://DeGette.house.gov/contact/email-me")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Delaney", url: "http://Delaney.house.gov/contact/email-me")
Rep.create(first_name: "Scott", first_three: "Sco", last_name: "DesJarlais", url: "http://DesJarlais.house.gov/contact/email-me")
Rep.create(first_name: "Sean", first_three: "Sea", last_name: "Duffy", url: "http://Duffy.house.gov/contact/email-me")
Rep.create(first_name: "Keith", first_three: "Kei", last_name: "Ellison", url: "http://Ellison.house.gov/contact/email-me")
Rep.create(first_name: "Jeff", first_three: "Jef", last_name: "Fortenberry", url: "http://Fortenberry.house.gov/contact/email-me")
Rep.create(first_name: "Bill", first_three: "Bil", last_name: "Foster", url: "http://Foster.house.gov/contact/email-me")
Rep.create(first_name: "Garret", first_three: "Gar", last_name: "Graves", url: "http://Graves.house.gov/contact/email-me")
Rep.create(first_name: "Sam", first_three: "Sam", last_name: "Graves", url: "http://Graves.house.gov/contact/email-me")
Rep.create(first_name: "Jeb", first_three: "Jeb", last_name: "Hensarling", url: "http://Hensarling.house.gov/contact/email-me")
Rep.create(first_name: "Jared", first_three: "Jar", last_name: "Huffman", url: "http://Huffman.house.gov/contact/email-me")
Rep.create(first_name: "Randy", first_three: "Ran", last_name: "Hultgren", url: "http://Hultgren.house.gov/contact/email-me")
Rep.create(first_name: "Hakeem", first_three: "Hak", last_name: "Jeffries", url: "http://Jeffries.house.gov/contact/email-me")
Rep.create(first_name: "Joe", first_three: "Joe", last_name: "Wilson", url: "http://JoeWilson.house.gov/contact/email-me")
Rep.create(first_name: "Derek", first_three: "Der", last_name: "Kilmer", url: "http://Kilmer.house.gov/contact/email-me")
Rep.create(first_name: "Steve", first_three: "Ste", last_name: "King", url: "https://steveking.house.gov/contact")
Rep.create(first_name: "Doug", first_three: "Dou", last_name: "LaMalfa", url: "http://LaMalfa.house.gov/contact/email-me")
Rep.create(first_name: "Leonard", first_three: "Leo", last_name: "Lance", url: "http://Lance.house.gov/contact/email-me")
Rep.create(first_name: "Barbara", first_three: "Bar", last_name: "Lee", url: "http://Lee.house.gov/contact/email-me")
Rep.create(first_name: "Michael", first_three: "Mic", last_name: "McCaul", url: "http://McCaul.house.gov/contact/email-me")
Rep.create(first_name: "Tom", first_three: "Tom", last_name: "McClintock", url: "http://McClintock.house.gov/contact/email-me")
Rep.create(first_name: "Jim", first_three: "Jim", last_name: "McGovern", url: "http://McGovern.house.gov/contact/email-me")
Rep.create(first_name: "Jerry", first_three: "Jer", last_name: "McNerney", url: "http://McNerney.house.gov/contact/email-me")
Rep.create(first_name: "Mark", first_three: "Mar", last_name: "Meadows", url: "http://Meadows.house.gov/contact/email-me")
Rep.create(first_name: "Pat", first_three: "Pat", last_name: "Meehan", url: "http://Meehan.house.gov/contact/email-me")
Rep.create(first_name: "Grace", first_three: "Gra", last_name: "Meng", url: "http://Meng.house.gov/contact/email-me")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Thompson", url: "http://MikeThompson.house.gov/contact/email-me")
Rep.create(first_name: "Rick", first_three: "Ric", last_name: "Nolan", url: "http://Nolan.house.gov/contact/email-me")
Rep.create(first_name: "Donald", first_three: "Don", last_name: "Norcross", url: "http://Norcross.house.gov/contact/email-me")
Rep.create(first_name: "Pete", first_three: "Pet", last_name: "Olson", url: "http://Olson.house.gov/contact/email-me")
Rep.create(first_name: "Bill", first_three: "Bil", last_name: "Pascrell", url: "http://Pascrell.house.gov/contact/email-me")
Rep.create(first_name: "Chellie", first_three: "Che", last_name: "Pingree", url: "http://Pingree.house.gov/contact/email-me")
Rep.create(first_name: "Robert", first_three: "Rob", last_name: "Pittenger", url: "http://Pittenger.house.gov/contact/email-me")
Rep.create(first_name: "Mark", first_three: "Mar", last_name: "Pocan", url: "http://Pocan.house.gov/contact/email-me")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Quigley", url: "http://Quigley.house.gov/contact/email-me")
Rep.create(first_name: "Robin", first_three: "Rob", last_name: "Kelly", url: "http://RobinKelly.house.gov/contact/email-me")
Rep.create(first_name: "Dana", first_three: "Dan", last_name: "Rohrabacher", url: "http://Rohrabacher.house.gov/contact/email-me")
Rep.create(first_name: "Peter", first_three: "Pet", last_name: "Roskam", url: "http://Roskam.house.gov/contact/email-me")
Rep.create(first_name: "Keith", first_three: "Kei", last_name: "Rothfus", url: "http://Rothfus.house.gov/contact/email-me")
Rep.create(first_name: "Mark", first_three: "Mar", last_name: "Sanford", url: "http://Sanford.house.gov/contact/email-me")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Sarbanes", url: "http://Sarbanes.house.gov/contact/email-me")
Rep.create(first_name: "Sean", first_three: "Sea", last_name: "Maloney", url: "http://SeanMaloney.house.gov/contact/email-me")
Rep.create(first_name: "José", first_three: "Jos", last_name: "Serrano", url: "http://Serrano.house.gov/contact/email-me")
Rep.create(first_name: "Terri", first_three: "Ter", last_name: "Sewell", url: "http://Sewell.house.gov/contact/email-me")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Shimkus", url: "http://Shimkus.house.gov/contact/email-me")
Rep.create(first_name: "Chris", first_three: "Chr", last_name: "Stewart", url: "http://Stewart.house.gov/contact/email-me")
Rep.create(first_name: "Susan", first_three: "Sus", last_name: "Brooks", url: "http://SusanBrooks.house.gov/contact/email-me")
Rep.create(first_name: "Mark", first_three: "Mar", last_name: "Takano", url: "http://Takano.house.gov/contact/email-me")
Rep.create(first_name: "Dina", first_three: "Din", last_name: "Titus", url: "http://Titus.house.gov/contact/email-me")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Turner", url: "http://Turner.house.gov/contact/email-me")
Rep.create(first_name: "Juan", first_three: "Jua", last_name: "Vargas", url: "http://Vargas.house.gov/contact/email-me")
Rep.create(first_name: "Marc", first_three: "Mar", last_name: "Veasey", url: "http://Veasey.house.gov/contact/email-me")
Rep.create(first_name: "Pete", first_three: "Pet", last_name: "Visclosky", url: "http://Visclosky.house.gov/contact/email-me")
Rep.create(first_name: "Ann", first_three: "Ann", last_name: "Wagner", url: "http://Wagner.house.gov/contact/email-me")
Rep.create(first_name: "Tim", first_three: "Tim", last_name: "Walz", url: "http://Walz.house.gov/contact/email-me")
Rep.create(first_name: "Randy", first_three: "Ran", last_name: "Weber", url: "http://Weber.house.gov/contact/email-me")
Rep.create(first_name: "Roger", first_three: "Rog", last_name: "Williams", url: "http://Williams.house.gov/contact/email-me")
Rep.create(first_name: "Kevin", first_three: "Kev", last_name: "Yoder", url: "http://Yoder.house.gov/contact/email-me")
Rep.create(first_name: "Ted", first_three: "Ted", last_name: "Yoho", url: "http://Yoho.house.gov/contact/email-me")
Rep.create(first_name: "Bobby", first_three: "Bob", last_name: "Rush", url: "http://Rush.house.gov/contact/email-me")
Rep.create(first_name: "Adrian", first_three: "Adr", last_name: "Smith", url: "http://AdrianSmith.house.gov/contact-me/email-me")
Rep.create(first_name: "Al", first_three: "Al", last_name: "Green", url: "http://AlGreen.house.gov/contact-me/email-me")
Rep.create(first_name: "Bob", first_three: "Bob", last_name: "Brady", url: "http://Brady.house.gov/contact-me/email-me")
Rep.create(first_name: "Mo", first_three: "Mo", last_name: "Brooks", url: "http://Brooks.house.gov/contact-me/email-me")
Rep.create(first_name: "Joseph", first_three: "Jos", last_name: "Crowley", url: "http://Crowley.house.gov/contact-me/email-me")
Rep.create(first_name: "Suzan", first_three: "Suz", last_name: "DelBene", url: "http://DelBene.house.gov/contact-me/email-me")
Rep.create(first_name: "Michael", first_three: "Mic", last_name: "Doyle", url: "http://Doyle.house.gov/contact-me/email-me")
Rep.create(first_name: "Jimmy", first_three: "Jim", last_name: "Duncan", url: "http://Duncan.house.gov/contact-me/email-me")
Rep.create(first_name: "Chuck", first_three: "Chu", last_name: "Fleischmann", url: "http://Fleischmann.house.gov/contact-me/email-me")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Garamendi", url: "http://Garamendi.house.gov/contact-me/email-me")
Rep.create(first_name: "Paul", first_three: "Pau", last_name: "Gosar", url: "http://Gosar.house.gov/contact-me/email-me")
Rep.create(first_name: "Andy", first_three: "And", last_name: "Harris", url: "http://Harris.house.gov/contact-me/email-me")
Rep.create(first_name: "Jim", first_three: "Jim", last_name: "Himes", url: "http://Himes.house.gov/contact-me/email-me")
Rep.create(first_name: "Duncan", first_three: "Dun", last_name: "Hunter", url: "http://Hunter.house.gov/contact-me/email-me")
Rep.create(first_name: "Jeff", first_three: "Jef", last_name: "Duncan", url: "http://JeffDuncan.house.gov/contact-me/email-me")
Rep.create(first_name: "Walter", first_three: "Wal", last_name: "Jones", url: "http://Jones.house.gov/contact-me/email-me")
Rep.create(first_name: "James", first_three: "Jam", last_name: "Langevin", url: "http://Langevin.house.gov/contact-me/email-me")
Rep.create(first_name: "Sander", first_three: "San", last_name: "Levin", url: "http://Levin.house.gov/contact-me/email-me")
Rep.create(first_name: "Frank", first_three: "Fra", last_name: "LoBiondo", url: "http://LoBiondo.house.gov/contact-me/email-me")
Rep.create(first_name: "Frank", first_three: "Fra", last_name: "Lucas", url: "http://Lucas.house.gov/contact-me/email-me")
Rep.create(first_name: "Stephen", first_three: "Ste", last_name: "Lynch", url: "http://Lynch.house.gov/contact-me/email-me")
Rep.create(first_name: "Betty", first_three: "Bet", last_name: "McCollum", url: "http://McCollum.house.gov/contact-me/email-me")
Rep.create(first_name: "Gregory", first_three: "Gre", last_name: "Meeks", url: "http://Meeks.house.gov/contact-me/email-me")
Rep.create(first_name: "Jerrold", first_three: "Jer", last_name: "Nadler", url: "http://Nadler.house.gov/contact-me/email-me")
Rep.create(first_name: "Grace", first_three: "Gra", last_name: "Napolitano", url: "http://Napolitano.house.gov/contact-me/email-me")
Rep.create(first_name: "Kristi", first_three: "Kri", last_name: "Noem", url: "http://noem.house.gov/index.cfm/email-kristi")
Rep.create(first_name: "Frank", first_three: "Fra", last_name: "Pallone", url: "http://Pallone.house.gov/contact-me/email-me")
Rep.create(first_name: "Steve", first_three: "Ste", last_name: "Pearce", url: "http://Pearce.house.gov/contact-me/email-me")
Rep.create(first_name: "Nancy", first_three: "Nan", last_name: "Pelosi", url: "http://Pelosi.house.gov/contact-me/email-me")
Rep.create(first_name: "Collin", first_three: "Col", last_name: "Peterson", url: "http://Peterson.house.gov/contact-me/email-me")
Rep.create(first_name: "Dave", first_three: "Dav", last_name: "Reichert", url: "http://Reichert.house.gov/contact-me/email-me")
Rep.create(first_name: "Todd", first_three: "Tod", last_name: "Rokita", url: "http://Rokita.house.gov/contact-me/email-me")
Rep.create(first_name: "Ileana", first_three: "Ile", last_name: "Ros-Lehtinen", url: "http://Ros-Lehtinen.house.gov/contact-me/email-me")
Rep.create(first_name: "Steve", first_three: "Ste", last_name: "Scalise", url: "http://Scalise.house.gov/contact-me/email-me")
Rep.create(first_name: "Scott", first_three: "Sco", last_name: "Tipton", url: "http://Tipton.house.gov/contact-me/email-me")
Rep.create(first_name: "Tony", first_three: "Ton", last_name: "Cardenas", url: "https://cardenas.house.gov/contact-me/email-me")
Rep.create(first_name: "David", first_three: "Dav", last_name: "Cicilline", url: "https://cicilline.house.gov/contact-me/email-me")
Rep.create(first_name: "Katherine", first_three: "Kat", last_name: "Clark", url: "https://katherineclark.house.gov/index.cfm/email-me")
Rep.create(first_name: "Jim", first_three: "Jim", last_name: "Clyburn", url: "https://clyburn.house.gov/contact-me/email-me")
Rep.create(first_name: "Danny", first_three: "Dan", last_name: "Davis", url: "https://davis.house.gov/email-me/")
Rep.create(first_name: "Charlie", first_three: "Cha", last_name: "Dent", url: "https://dent.house.gov/?p=ContactForm")
Rep.create(first_name: "Ron", first_three: "Ron", last_name: "DeSantis", url: "https://desantis.house.gov/email-me")
Rep.create(first_name: "Mario", first_three: "Mar", last_name: "Díaz-Balart", url: "http://mariodiazbalart.house.gov/contact-mario/write-rep-diaz-balart")
Rep.create(first_name: "Debbie", first_three: "Deb", last_name: "Dingell", url: "https://debbiedingellforms.house.gov/contact/")
Rep.create(first_name: "Eliot", first_three: "Eli", last_name: "Engel", url: "https://engel.house.gov/write-your-rep1/")
Rep.create(first_name: "Rodney", first_three: "Rod", last_name: "Frelinghuysen", url: "https://frelinghuysen.house.gov/contact-form/")
Rep.create(first_name: "Marcia", first_three: "Mar", last_name: "Fudge", url: "https://fudge.house.gov/email-me/")
Rep.create(first_name: "Tulsi", first_three: "Tul", last_name: "Gabbard", url: "https://gabbard.house.gov/connect/share-your-ideas")
Rep.create(first_name: "Ruben", first_three: "Rub", last_name: "Gallego", url: "https://rubengallego.house.gov/contact/email")
Rep.create(first_name: "Thomas", first_three: "Tho", last_name: "Garrett", url: "https://tomgarrett.house.gov/contact/email")
Rep.create(first_name: "Vicente", first_three: "Vic", last_name: "Gonzalez", url: "https://gonzalez.house.gov/contact/email")
Rep.create(first_name: "Trey", first_three: "Tre", last_name: "Gowdy", url: "https://gowdyforms.house.gov/forms/writeyourrep/")
Rep.create(first_name: "Kay", first_three: "Kay", last_name: "Granger", url: "http://kaygranger.house.gov/contact-kay/email-me")
Rep.create(first_name: "Raúl", first_three: "Raú", last_name: "Grijalva", url: "https://grijalva.house.gov/email-raul")
Rep.create(first_name: "Brett", first_three: "Bre", last_name: "Guthrie", url: "http://brettguthrieforms.house.gov/contact/")
Rep.create(first_name: "Luis", first_three: "Lui", last_name: "Gutiérrez", url: "http://gutierrezforms.house.gov/contact/")
Rep.create(first_name: "Gregg", first_three: "Gre", last_name: "Harper", url: "http://harper.house.gov/contact-gregg/email-gregg")
Rep.create(first_name: "Alcee", first_three: "Alc", last_name: "Hastings", url: "http://alceehastings.house.gov/contact/")
Rep.create(first_name: "Dennis", first_three: "Den", last_name: "Heck", url: "https://dennyheck.house.gov/contact/email-me")
Rep.create(first_name: "Steny", first_three: "Ste", last_name: "Hoyer", url: "https://hoyer.house.gov/email-steny")
Rep.create(first_name: "Richard", first_three: "Ric", last_name: "Hudson", url: "https://hudson.house.gov/email-me/")
Rep.create(first_name: "Darrell", first_three: "Dar", last_name: "Issa", url: "http://issa.house.gov/contact")
Rep.create(first_name: "David", first_three: "Dav", last_name: "Joyce", url: "https://joyce.house.gov/email-me/")
Rep.create(first_name: "Joseph", first_three: "Jos", last_name: "Kennedy", url: "https://kennedy.house.gov/contact/email-me")
Rep.create(first_name: "Raúl", first_three: "Raú", last_name: "Labrador", url: "https://labrador.house.gov/email-me/")
Rep.create(first_name: "Rick", first_three: "Ric", last_name: "Larsen", url: "http://larsen.house.gov/contact-rick/email-rick")
Rep.create(first_name: "Dan", first_three: "Dan", last_name: "Lipinski", url: "https://lipinski.house.gov/contact-form/")
Rep.create(first_name: "Billy", first_three: "Bil", last_name: "Long", url: "https://long.house.gov/email-billy/")
Rep.create(first_name: "Mia", first_three: "Mia", last_name: "Love", url: "https://love.house.gov/email-me/")
Rep.create(first_name: "Thomas", first_three: "Tho", last_name: "Massie", url: "http://massieforms.house.gov/contact/")
Rep.create(first_name: "Kevin", first_three: "Kev", last_name: "McCarthy", url: "https://kevinmccarthy.house.gov/contact/email-me")
Rep.create(first_name: "David", first_three: "Dav", last_name: "McKinley", url: "https://mckinley.house.gov/email-me/")
Rep.create(first_name: "Gwen", first_three: "Gwe", last_name: "Moore", url: "https://gwenmoore.house.gov/index.cfm?sectionid=58")
Rep.create(first_name: "Beto", first_three: "Bet", last_name: "ORourke", url: "http://orourke.house.gov/correspondence/")
Rep.create(first_name: "Erik", first_three: "Eri", last_name: "Paulsen", url: "https://paulsen.house.gov/contact-me/")
Rep.create(first_name: "Donald", first_three: "Don", last_name: "Payne", url: "http://payne.house.gov/contact/email-me")
Rep.create(first_name: "Scott", first_three: "Sco", last_name: "Peters", url: "https://scottpeters.house.gov/contact/email-me")
Rep.create(first_name: "Ted", first_three: "Ted", last_name: "Poe", url: "https://poe.house.gov/contact-form")
Rep.create(first_name: "David", first_three: "Dav", last_name: "Price", url: "https://priceforms.house.gov/contact/")
Rep.create(first_name: "Jim", first_three: "Jim", last_name: "Renacci", url: "https://renacci.house.gov/index.cfm/contact-form")
Rep.create(first_name: "Cedric", first_three: "Ced", last_name: "Richmond", url: "https://richmond.house.gov/contact-cedric/email-me")
Rep.create(first_name: "Martha", first_three: "Mar", last_name: "Roby", url: "https://roby.house.gov/contact-me")
Rep.create(first_name: "Dennis", first_three: "Den", last_name: "Ross", url: "http://dennisross.house.gov/contact/")
Rep.create(first_name: "Ed", first_three: "Ed", last_name: "Royce", url: "http://royce.house.gov/contact/zipcheck.htm")
Rep.create(first_name: "Dutch", first_three: "Dut", last_name: "Ruppersberger", url: "http://ruppersberger.house.gov/contact-dutch/email-dutch")
Rep.create(first_name: "Linda", first_three: "Lin", last_name: "Sanchez", url: "https://lindasanchez.house.gov/contact/email")
Rep.create(first_name: "Jan", first_three: "Jan", last_name: "Schakowsky", url: "https://schakowsky.house.gov/write-to-congresswoman-jan-schakowsky/")
Rep.create(first_name: "Adam", first_three: "Ada", last_name: "Schiff", url: "http://schiff.house.gov/contact")
Rep.create(first_name: "Brad", first_three: "Bra", last_name: "Sherman", url: "https://sherman.house.gov/contact/contact-congressman-sherman-form")
Rep.create(first_name: "Bill", first_three: "Bil", last_name: "Shuster", url: "https://shuster.house.gov/contact-form/")
Rep.create(first_name: "Kyrsten", first_three: "Kyr", last_name: "Sinema", url: "https://sinemaforms.house.gov/forms/writeyourrep/")
Rep.create(first_name: "Louise", first_three: "Lou", last_name: "Slaughter", url: "https://louise.house.gov/contact/email-louise")
Rep.create(first_name: "Niki", first_three: "Nik", last_name: "Tsongas", url: "https://tsongas.house.gov/e-mail-niki/")
Rep.create(first_name: "Filemon", first_three: "Fil", last_name: "Velazquez", url: "https://velazquez.house.gov/contact/email")
Rep.create(first_name: "Nydia", first_three: "Nyd", last_name: "Vela", url: "https://vela.house.gov/contact")
Rep.create(first_name: "Greg", first_three: "Gre", last_name: "Walden", url: "https://walden.house.gov/contact-greg/email-me")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Yarmuth", url: "https://yarmuth.house.gov/contact-john2/")
Rep.create(first_name: "Doug", first_three: "Dou", last_name: "Collins", url: "https://dougcollins.house.gov/email-me/")
Rep.create(first_name: "Hal", first_three: "Hal", last_name: "Rogers", url: "https://halrogers.house.gov/email")
Rep.create(first_name: "Jason", first_three: "Jas", last_name: "Smith", url: "http://jasonsmith.house.gov/contact/email-jason")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Lewis", url: "https://johnlewis.house.gov/contact-me/email")
Rep.create(first_name: "Lamar", first_three: "Lam", last_name: "Smith", url: "https://lamarsmith.house.gov/contact/email-lamar")
Rep.create(first_name: "Lynn", first_three: "Lyn", last_name: "Jenkins", url: "https://lynnjenkins.house.gov/contact-me/")
Rep.create(first_name: "Mike", first_three: "Mik", last_name: "Rogers", url: "https://mikerogers.house.gov/contact-mike/email-me")
Rep.create(first_name: "Susan", first_three: "Sus", last_name: "Davis", url: "https://susandavis.house.gov/contact")
Rep.create(first_name: "Tim", first_three: "Tim", last_name: "Ryan", url: "http://timryanforms.house.gov/contact/")
Rep.create(first_name: "John", first_three: "Joh", last_name: "Carter", url: "https://carter.house.gov/email-john2/")
